version: '3'
services:
  inventory-api:
    ports:
      - "5000:5000"
    image:
      willnx/vlab-inventory-api
    volumes:
      - ./vlab_inventory_api:/usr/lib/python3.6/site-packages/vlab_inventory_api
    command: ["python3", "app.py"]

  inventory-worker:
    image:
      willnx/vlab-inventory-worker
    volumes:
      - ./vlab_inventory_api:/usr/lib/python3.6/site-packages/vlab_inventory_api

  inventory-broker:
    image:
      rabbitmq:3.7-alpine
